// f - from, old URL
// t - to, new URL

let redirectionsTab = [
    { f: `pagepro.co/index.html`, t: `pagepro.co/` },
    { f: `/our-work.html`, t: `/works` },
    { f: `/services.html`, t: `/services` },
    { f: `/about.html`, t: `/about` },
    { f: `/career.html`, t: `/career` },
    { f: `/contact.html`, t: `/contact` },
    { f: `/privacy.html`, t: `/privacy-policy` },
    { f: `/cookies.html`, t: `/cookies` },
    { f: `/310.html`, t: `/works/310` },
    { f: `/acrf.html`, t: `/works/acrf` },
    { f: `/blockchain-agreements.html`, t: `/works/blockchain-agreements` },
    { f: `/cryptocurrency-arbitrage.html`, t: `/works/cryptocurrency-arbitrage` },
    { f: `/dekra.html`, t: `/works/dekra` },
    { f: `/frontend-app.html`, t: `/works/frontend-app` },
    { f: `/gatedtalent-website.html`, t: `/works/gatedtalent-website` },
    { f: `/gatedtalent.html`, t: `/works/gatedtalent` },
    { f: `/hawksman.html`, t: `/works/hawksman` },
    { f: `/hurt-koszulkowo.html`, t: `/works/hurt-koszulkowo` },
    { f: `/isv-online.html`, t: `/works/isv-online` },
    { f: `/karina-papadopoulos.html`, t: `/works/karina-papadopoulos` },
    { f: `/krd.html`, t: `/works/krd` },
    { f: `/my-name-flow.html`, t: `/works/my-name-flow` },
    { f: `/outside-the-lines.html`, t: `/works/outside-the-lines` },
    { f: `/woodland-girls.html`, t: `/works/woodland-girls` },
    { f: `/wroc-sharp.html`, t: `/works/wroc-sharp` },
    { f: `/fronted-development.html`, t: `/services/fronted-development` },
    { f: `/nodejs-development.html`, t: `/services/nodejs-development` },
    { f: `/react-development.html`, t: `/services/react-development` },
    { f: `/react-native-development.html`, t: `/services/react-native-development` },
    { f: `/storybook-development.html`, t: `/services/storybook-development` },
    { f: `/wordpress-development.html`, t: `/services/wordpress-development` },
    { f: `/career-frontend.html`, t: `/career/frontend` },
    { f: `/career-frontend-dev.html`, t: `/career/frontend-dev` },
    { f: `/career-javascript.html`, t: `/career/javascript` },
    { f: `/career-marketing-manager.html`, t: `/career/marketing-manager` },
    { f: `/career-netdev.html`, t: `/career/netdev` },
    { f: `/career-qa.html`, t: `/career/qa` },
    { f: `/career-react.html`, t: `/career/react` },
    { f: `/career-sales.html`, t: `/career/sales` },
    { f: `/career-technical-acount.html`, t: `/career/technical-acount` },
    { f: `/career-wordpress.html`, t: `/career/wordpress` },
]

module.exports = { redirectionsTab };